name: Rozena front pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
       sudo apt-get install -y qt6-default
    
    - name: Build project
      run: |
       cd Front
       qmake && make
    
    - name: Run tests
      run: ls

