name: Rozena front pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
       sudo apt-get install libxkbcommon-x11-0
       sudo apt-get install libxcb-icccm4
       sudo apt-get install libxcb-image0
       wget https://download.qt.io/official_releases/online_installers/qt-unified-linux-x64-online.run
       chmod +x qt-unified-linux-x64-online.run
       ./qt-unified-linux-x64-online.run --script tools/remote_install.qs
    
    - name: Build project
      run: |
       cd Front
       qmake && make
    
    - name: Run tests
      run: ls

